### ISSUE TITLE
Fatal Error issue: Uncaught TypeError: array_key_exists

### ISSUE THREAD

**Issue by samjco** [qriouslad/admin-site-enhancements#9]
Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in /var/www/html/files/addons/admin-site-enhancements/bootstrap.php:79 Stack trace: #0 /var/www/html/files/addons/admin-site-enhancements/bootstrap.php(25): Admin_Site_Enhancements->__construct() #1 /var/www/html/files/addons/admin-site-enhancements/bootstrap.php(861): Admin_Site_Enhancements::get_instance() #2 /var/www/html/files/addons/admin-site-enhancements/admin-site-enhancements.php(111): require_once('...') #3 /var/www/html/wp-settings.php(473): include_once('...') #4 /var/www/html/wp-config.php(146): require_once('...') #5 /var/www/html/wp-load.php(50): require_once('...') #6 /var/www/html/wp-blog-header.php(13): require_once('...') #7 /var/www/html/index.php(17): require('...') #8 {main} thrown in /var/www/html/files/addons/admin-site-enhancements/bootstrap.php on line 79

**Comment by qriouslad** [comment]
When did you see this error?
